Changes

diff --git a/azure.yaml b/azure.yaml
--- a/azure.yaml
+++ b/azure.yaml
@@ -7,40 +7,40 @@ infra:
   provider: bicep
   path: bicep
 hooks:
-  preprovision:
-    posix:
-      interactive: false
-      continueOnError: false
-      shell: sh
-      run: |
-        # Check if PREPARE is not set to true
-        if [[ "$PREPARE" == "true" ]]; then
-          # Check if Docker command exists
-          if command -v docker &> /dev/null; then
-            echo "Building Docker Image"
-            docker buildx build --no-cache -f scripts/Dockerfile-provision -t azd-provision scripts
-            docker run --rm -v $(pwd):/workspace -v "${HOME}/.azure:/root/.azure" -e AZURE_CONFIG_DIR=/root/.azure azd-provision /usr/local/bin/preprovision.sh -s ${AZURE_SUBSCRIPTION_ID}
-            sleep 5
-          else
-            echo "Docker is not installed."
-            exit 1
-          fi
-        fi
+  # preprovision:
+  #   posix:
+  #     interactive: false
+  #     continueOnError: false
+  #     shell: sh
+  #     run: |
+  #       # Check if PREPARE is not set to true
+  #       if [[ "$PREPARE" == "true" ]]; then
+  #         # Check if Docker command exists
+  #         if command -v docker &> /dev/null; then
+  #           echo "Building Docker Image"
+  #           docker buildx build --no-cache -f scripts/Dockerfile-provision -t azd-provision scripts
+  #           docker run --rm -v $(pwd):/workspace -v "${HOME}/.azure:/root/.azure" -e AZURE_CONFIG_DIR=/root/.azure azd-provision /usr/local/bin/preprovision.sh -s ${AZURE_SUBSCRIPTION_ID}
+  #           sleep 5
+  #         else
+  #           echo "Docker is not installed."
+  #           exit 1
+  #         fi
+  #       fi
 
-    windows:
-      interactive: false
-      continueOnError: false
-      shell: pwsh
-      run: |
-        if (-Not (Get-Command "docker" -ErrorAction SilentlyContinue))
-        {
-          Write-Host "no docker"
-          exit
-        }
-        Write-Host "Building Docker Image"
-        docker buildx build --no-cache -f scripts/Dockerfile-provision -t azd-provision scripts
-        docker run --rm -v ${pwd}:/workspace -v "$($HOME)/.azure:/root/.azure" -e AZURE_CONFIG_DIR=/root/.azure azd-provision /usr/local/bin/preprovision.sh -s $env:AZURE_SUBSCRIPTION_ID
-        Start-Sleep -Seconds 5
+  #   windows:
+  #     interactive: false
+  #     continueOnError: false
+  #     shell: pwsh
+  #     run: |
+  #       if (-Not (Get-Command "docker" -ErrorAction SilentlyContinue))
+  #       {
+  #         Write-Host "no docker"
+  #         exit
+  #       }
+  #       Write-Host "Building Docker Image"
+  #       docker buildx build --no-cache -f scripts/Dockerfile-provision -t azd-provision scripts
+  #       docker run --rm -v ${pwd}:/workspace -v "$($HOME)/.azure:/root/.azure" -e AZURE_CONFIG_DIR=/root/.azure azd-provision /usr/local/bin/preprovision.sh -s $env:AZURE_SUBSCRIPTION_ID
+  #       Start-Sleep -Seconds 5
 
   # postprovision:
   #   posix:
