Updated chart

diff --git a/charts/airflow-dags/templates/dag-csv-job.yaml b/charts/airflow-dags/templates/dag-csv-job.yaml
--- a/charts/airflow-dags/templates/dag-csv-job.yaml
+++ b/charts/airflow-dags/templates/dag-csv-job.yaml
@@ -93,7 +93,15 @@ data:
     url_basename=$(basename "${URL}")
     echo "Derived filename from URL: ${url_basename}"
     echo "Downloading file from ${URL} to ${url_basename}"
-    curl -so "${url_basename}" "${URL}"
+
+    if ! curl -so "${url_basename}" "${URL}"; then
+      echo "Failed to download file"
+      sleep 300000
+      exit 1
+    fi
+    echo "Successfully downloaded file"
+    sleep 300000
+
     echo "Extracting tar.gz archive..."
     mkdir -p extracted_files
     tar -xzf "${url_basename}" --strip-components=1 -C extracted_files
